<h1><div><i class="fa fa-info"></i></div>About the SWAMP</h1>

<ol class="breadcrumb">
	<li><a href="#home"><i class="fa fa-home"></i>Home</a></li>
	<li><i class="fa fa-info"></i>About</li>
</ol>

<p>The Software Assurance Marketplace (SWAMP) is committed to bringing a transformative change to the national software assurance landscape by providing a national marketplace that provides continuous software assurance capabilities to researchers and developers. By providing software assurance researchers, tool developers, tool users and educators who train our workforce a suite of secure and dependable analysis services, the Software Assurance Marketplace will reduce the number of vulnerabilities deployed in software.</p>

<p>Researchers who develop new software assurance tools and methodologies will use the repositories and cyberinfrastructure offered by the marketplace to improve their technologies and tools, while software developers and adopters will use the same services to hunt for vulnerabilities in their software. Educators will use these services to offer hands-on experience in software assurance techniques to their students.</p>

<p>By facilitating the sharing of tools, techniques, information, experiences and resources, the Software Assurance Marketplace will:</p>
<ul>
	<li>Help advance the quality and adoption rate of software assurance tools;</li>
	<li>Lower the threshold for using them; and</li>
	<li>Make it easier to interpret and use the resulting output.</li>
</ul>

<h2>Why Use the SWAMP?</h2>
<p>Different people use the SWAMP for different reasons. Why you participate in the Software Assurance Marketplace depends on your goals.  Be assured that however you may choose to use the SWAMP, you are in full control of your data.  You decide whether to make your results public or private or shared with just those you trust.</p>

<ul class="initial">
	<li>
		<h3>Software Developers</h3>
		use the SWAMP with the available software assurance tools to analyze their software. If they learn about a security weakness in their code, they can fix it.  Finding the weaknesses is the hard part. Manually reviewing code to find all the security weaknesses and vulnerabilities in software is tedious and labor-intensive job. Each operating system that runs their software can present new opportunities for security weaknesses. The SWAMP automates finding the weaknesses in their code on multiple operating systems.
	</li>
	<li>
		<h3>SwA Tool Developers</h3>
		use the SWAMP to help software developers assess their code. Developing static code analysis tools to automate the detection of security weaknesses and vulnerabilities is a great service to the software community at large!  But it is a challenging endeavor.  The SWAMP makes their life easier with its wide assortment of software packages to test against and other tools to compare their tool against.
	</li>
	<li>
		<h3>Educators</h3>
		use the SWAMP to help their Students learn about the importance of software assurance.  Many software developers do not use software assurance tools because either they are unaware of the available tools or they are too busy to learn how to use static code analysis tools effectively. The SWAMP provides a one-stop shop equipped with the most instructive code examples and the best SwA tools for the most used programming languages. Plus, the SWAMP makes training the next generation to use software assurance techniques available at no cost!
	</li>
	<li>
		<h3>IT Infrastructure Operators</h3>
		use the SWAMP to improve their organization’s return on investment. No organization knowingly would put itself at risk operating with software having security vulnerabilities. Learning whether a piece of software is secure can be a time-consuming, expensive endeavor – especially considering all the software components in IT operations.  Organizations concerned with supply chain risk management find the SWAMP a cost-effective means towards a sound software assurance policy.
	</li>
	<li>
		<h3>SwA Researchers</h3>
		use the SWAMP as a laboratory for discovery.  The SWAMP provides a big data center of software assessments generated by many SwA tools assessing hundreds of software packages on all common operating systems. The SWAMP offers a nicely equipped laboratory to researchers at no cost.
	</li>
</ul>

<h2>The SWAMP Team</h2>
<p>The SWAMP project is led by a <a href="https://continuousassurance.org/about-us/bios/" target="_blank">team</a> at the <a href="http://discovery.wisc.edu/morgridge/" target="_blank">Morgridge Institutes for Research</a> at the <a href="http://www.wisc.edu/" target="_blank">University of Wisconsin, Madison</a>.  The leaders and scientific team members of the Software Assurance Marketplace have a long and accomplished history of working together. Some of the joint work has taken place in the context of large collaborations that span a wide range of institutions, involve diverse groups of stakeholders and serve a broad range of needs and expectations. Over more than 10 years, team members have developed the interpersonal relationships and skills needed to lead the Software Assurance Marketplace to success. Team members recognize the challenges of working in complex environments and intend to translate the concept of the Software Assurance Marketplace into a force that advances the state of the art and promotes the adoption of technologies to improve our nation's cybersecurity.</p>

<h2>Join the SWAMP Community</h2>
<p style="padding-bottom:10px"><a target="_blank" class="subscribe" href2="https://lists.discovery.wisc.edu/mailman/listinfo/swampmail">Subscribe</a> to our mailing list. We'll notify you of events interesting to the SWAMP User Communities.</p>

<h2>SWAMP Funding and Support</h2>
<p>The SWAMP is funded by the Department of Homeland Security (DHS) Science and Technology Directorate, Homeland Security Advanced Research Projects Agency, Cyber Security Division (DHS S&T/HSARPA/CSD)</p>

<p><strong>SWAMP Version:</strong> <%= Version.build %></p>
